/* Auto-generated by genmsg_cpp for file /opt/ros/kinetic/share/std_msgs/msg/Float64.msg */
#ifndef STD_MSGS_MESSAGE_FLOAT64_H
#define STD_MSGS_MESSAGE_FLOAT64_H
#include "ros.hpp"
#include "Message.hpp"
#include <new>

namespace std_msgs
{
class Float64_ : public ros_echronos::Message {
  typedef Float64_ Type;

  public:
  Float64_();
  ~Float64_();
  virtual void generate_block_impl();
  virtual ros_echronos::Message_Descriptor * generate_descriptor();
  typedef double _data_type;
  double data;

  ros_echronos::Message_Descriptor * desc = NULL;
  typedef  ::std_msgs::Float64_  * Ptr;
  typedef  ::std_msgs::Float64_  * const ConstPtr;
}; // class Float64
typedef  ::std_msgs::Float64_ Float64;

typedef  ::std_msgs::Float64 Float64Ptr;
typedef  ::std_msgs::Float64 const Float64ConstPtr;


} // namespace std_msgs

#endif // STD_MSGS_MESSAGE_FLOAT64_H

