/* Auto-generated by genmsg_cpp for file ../owr_software/rover/src/owr_messages/msg/pwm.msg */
#ifndef OWR_MESSAGES_MESSAGE_PWM_H
#define OWR_MESSAGES_MESSAGE_PWM_H
#include "ros.hpp"
#include "Message.hpp"
#include <new>

namespace owr_messages
{
class pwm_ : public ros_echronos::Message {
  typedef pwm_ Type;

  public:
  pwm_();
  ~pwm_();
  virtual void generate_block_impl();
  virtual ros_echronos::Message_Descriptor * generate_descriptor();
  typedef ros_echronos::String _joint_type;
  ros_echronos::String joint;

  typedef int32_t _pwm_type;
  int32_t pwm;

  typedef double _targetVel_type;
  double targetVel;

  typedef double _currentVel_type;
  double currentVel;

  typedef double _currentPos_type;
  double currentPos;

  typedef double _targetPos_type;
  double targetPos;

  ros_echronos::Message_Descriptor * desc = NULL;
  typedef  ::owr_messages::pwm_  * Ptr;
  typedef  ::owr_messages::pwm_  * const ConstPtr;
}; // class pwm
typedef  ::owr_messages::pwm_ pwm;

typedef  ::owr_messages::pwm pwmPtr;
typedef  ::owr_messages::pwm const pwmConstPtr;


} // namespace owr_messages

#endif // OWR_MESSAGES_MESSAGE_PWM_H

