/* Auto-generated by genmsg_cpp for file ../owr_software/rover/src/owr_messages/msg/science.msg */
#ifndef OWR_MESSAGES_MESSAGE_SCIENCE_H
#define OWR_MESSAGES_MESSAGE_SCIENCE_H
#include "ros.hpp"
#include "Message.hpp"
#include <new>

namespace owr_messages {

    class science_ : public ros_echronos::Message {
        typedef science_ Type;

        public:
        science_();
        ~science_();
        virtual void generate_block_impl();
        virtual ros_echronos::Message_Descriptor * generate_descriptor();

        uint32_t temperature;
        uint32_t humidity;

        struct magnetism {
            float x;
            float y;
            float z;
        };
        struct magnetism m;

        uint16_t colour_temperature;
        uint16_t illuminance;

        ros_echronos::Message_Descriptor * desc = NULL;
        typedef  ::owr_messages::science_  * Ptr;
        typedef  ::owr_messages::science_  * const ConstPtr;
    }; // class science
typedef  ::owr_messages::science_ science;

typedef  ::owr_messages::science sciencePtr;
typedef  ::owr_messages::science const scienceConstPtr;

} // namespace owr_messages

#endif // OWR_MESSAGES_MESSAGE_SCIENCE_H

