#include "pwm_hw.h"

const struct pwm_prescale_struct pwm_prescale[NUM_DIV] = {
    {SYSCTL_PWMDIV_1, 1.0}, {SYSCTL_PWMDIV_2, 2.0}, {SYSCTL_PWMDIV_4, 4.0},
    {SYSCTL_PWMDIV_8, 8.0}, {SYSCTL_PWMDIV_16, 16.0}, {SYSCTL_PWMDIV_32, 32.0},
    {SYSCTL_PWMDIV_64, 64.0}};

const uint32_t sysctl_module = SYSCTL_PERIPH_PWM0;
const uint32_t pwm_module = PWM0_BASE;

const uint32_t 
    pwm_gen[PC] = {PWM_GEN_0, PWM_GEN_0, PWM_GEN_1, PWM_GEN_1,
                             PWM_GEN_2, PWM_GEN_2, PWM_GEN_3, PWM_GEN_3};
const uint32_t
    pwm_pair_gen[PPC] = {PWM_GEN_0, PWM_GEN_1, PWM_GEN_2,
                                    PWM_GEN_3};
const uint32_t 
    pwm_config = PWM_GEN_MODE_UP_DOWN | PWM_GEN_MODE_NO_SYNC 
               | PWM_GEN_MODE_DBG_RUN | PWM_GEN_MODE_GEN_NO_SYNC;

const struct pwm_out_struct pwm_out[PC] = {
    {PWM_OUT_0, PWM_OUT_0_BIT}, {PWM_OUT_1, PWM_OUT_1_BIT}, 
    {PWM_OUT_2, PWM_OUT_2_BIT}, {PWM_OUT_3, PWM_OUT_3_BIT}, 
    {PWM_OUT_4, PWM_OUT_4_BIT}, {PWM_OUT_5, PWM_OUT_5_BIT}, 
    {PWM_OUT_6, PWM_OUT_6_BIT}, {PWM_OUT_7, PWM_OUT_7_BIT}}; 


#ifdef PWMLIB_TEST_BOARD
const struct gpio_pin_struct gpio_pin[PC] = {
    {SYSCTL_PERIPH_GPIOB, GPIO_PORTB_BASE, GPIO_PIN_6, GPIO_PB6_M0PWM0},
    {SYSCTL_PERIPH_GPIOB, GPIO_PORTB_BASE, GPIO_PIN_7, GPIO_PB7_M0PWM1},
    {SYSCTL_PERIPH_GPIOB, GPIO_PORTB_BASE, GPIO_PIN_4, GPIO_PB4_M0PWM2},
    {SYSCTL_PERIPH_GPIOB, GPIO_PORTB_BASE, GPIO_PIN_5, GPIO_PB5_M0PWM3},
    {SYSCTL_PERIPH_GPIOE, GPIO_PORTE_BASE, GPIO_PIN_4, GPIO_PE4_M0PWM4},
    {SYSCTL_PERIPH_GPIOE, GPIO_PORTE_BASE, GPIO_PIN_5, GPIO_PE5_M0PWM5},
    {SYSCTL_PERIPH_GPIOC, GPIO_PORTC_BASE, GPIO_PIN_4, GPIO_PC4_M0PWM6},
    {SYSCTL_PERIPH_GPIOC, GPIO_PORTC_BASE, GPIO_PIN_5, GPIO_PC5_M0PWM7}};
#else
// Generic PCB constants
const struct gpio_pin_struct gpio_pin[PC] = {
    {SYSCTL_PERIPH_GPIOH, GPIO_PORTH_BASE, GPIO_PIN_0, GPIO_PH0_M0PWM0},
    {SYSCTL_PERIPH_GPIOH, GPIO_PORTH_BASE, GPIO_PIN_1, GPIO_PH1_M0PWM1},
    {SYSCTL_PERIPH_GPIOH, GPIO_PORTH_BASE, GPIO_PIN_2, GPIO_PH2_M0PWM2},
    {SYSCTL_PERIPH_GPIOH, GPIO_PORTH_BASE, GPIO_PIN_3, GPIO_PH3_M0PWM3},
    {SYSCTL_PERIPH_GPIOH, GPIO_PORTH_BASE, GPIO_PIN_4, GPIO_PH4_M0PWM4},
    {SYSCTL_PERIPH_GPIOH, GPIO_PORTH_BASE, GPIO_PIN_5, GPIO_PH5_M0PWM5},
    {SYSCTL_PERIPH_GPIOH, GPIO_PORTH_BASE, GPIO_PIN_6, GPIO_PH6_M0PWM6},
    {SYSCTL_PERIPH_GPIOH, GPIO_PORTH_BASE, GPIO_PIN_7, GPIO_PH7_M0PWM7}};
#endif

